# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: mishas/setup-bazelisk-action@v1
    - name: Install libgnat
      run: sudo apt-get install ghdl_llvm
    - uses: ghdl/setup-ghdl-ci@nightly
      with:
        backend: llvm
    - name: Mount bazel cache  # Optional
      uses: actions/cache@v1
      with:
        path: "~/.cache/bazel"
        key: bazel
    - run: ./test/test_documentation.sh
